def raise_exception():
  raise Exception('test exception')
